<?php

/**
 * @file Adds a BCC address to all e-mails sent by the website.
 */

/**
 * Add Bcc from settings into all outgoing email.
 *
 * @param array $message
 *   An array containing the message data.
 *
 * @see hook_mail_alter()
 */
function bcc_mail_alter(array &$message) {
  /** @var \Drupal\Core\Config\ConfigFactoryInterface $config */
  $config = \Drupal::service('config.factory');
  $bcc_config = $config->get('bcc.settings');

  if ($bcc_config->get('enable')) {
    $existingBcc = isset($message['headers']['Bcc']) ? $message['headers']['Bcc'] : '';
    $message['headers']['Bcc'] = implode(' ', array_merge(
        explode(' ', $existingBcc),
        [$bcc_config->get('bcc_mail')]
    ));
  }
}
