<?php

use Drupal\Core\Config\ConfigFactoryInterface;

function bcc_mail_alter(&$message) {
  /** @var ConfigFactoryInterface $config */
  $config = \Drupal::service('config.factory');
  $bcc_config = $config->get('bcc.settings');

  if ($bcc_config->get('enable')) {
    $existingBcc = isset($message['headers']['Bcc']) ? $message['headers']['Bcc'] : '';
    $message['headers']['Bcc'] = implode(' ', array_merge(
        explode(' ', $existingBcc),
        [$bcc_config->get('bcc_mail')]
    ));
  }
}